name: build rs-xtree

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-x64-${{ hashFiles('**/Cargo.lock') }}
      - name: Build x86_64
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu
          path: target/release/<BIN_NAME>
